name: Label New Issues as "To Do"
on:
  issues:
    types: [opened]
permissions:
    issues: write #explicity grant permission to manage issue
jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Label new issues as "To Do"
        uses: actions-ecosystem/action-add-labels@v1
        with:
            github_token: ${{ secrets.github_token}}
            labels: "To Do"